services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    EasyRdf_Sparql_Client:
      class:  EasyRdf_Sparql_Client
      arguments:
          $queryUri: '%env(SPARQL_QUERY_URI)%'
          $updateUri: '%env(SPARQL_UPDATE_URI)%'



    App\EasyRdf\EasyRdfClient:
        arguments: ['@EasyRdf_Sparql_Client']


    App\Rdf\Sparql\Client: '@App\EasyRdf\EasyRdfClient'

    Solarium_Client:
      class: Solarium\Client
      arguments:
        $options: { endpoint: {localhost : { host: '%env(SOLR_HOST)%', port: '%env(SOLR_PORT)%', path: '%env(SOLR_PATH)%', core: '%env(SOLR_CORE)%' }}}

    App\Solr\SolrClient:
      class: App\Solr\SolrClient
      arguments:
        $client: '@Solarium_Client'


    App\Rdf\Format\RdfFormatFactory:
        factory: [ 'App\Rdf\Format\RdfFormatFactory', 'loadDefault' ]


    App\Helper\xsdDateHelper:
        class: App\Helper\xsdDateHelper

    App\OpenSkos\Vocabulary\Controller\:
        resource: '../../src/OpenSkos/Vocabulary/Controller/*'
        tags: ['controller.service_arguments']
