openapi: 3.0.0
info:
  title      : "OpenSkos API"
  description: "TODO: DESCRIPTION"
  version    : "2.3"

servers:
  - "url": "http://api.openskos.local"
    "description": "Default local development server"

paths:
  /errors.{format}:
    get:
      "summary": ""
  /relationtypes.{format}:
    get:
      "summary": ""
  /relationtype/{id}.{format}:
    get:
      "summary": ""
  /vocab.{format}:
    get:
      "summary": ""
  /roles.{format}:
    get:
      "summary": ""
  /concept/{id}.{format}:
    get:
      "summary": ""
    delete:
      "summary": ""
  /concept.{format}:
    get:
      "summary": ""
  /concepts.{format}:
    get:
      "summary": "Retreive all (filtered) concepts"
      "parameters":
        - "type": "string"
          "name": "format"
          "example": "json"
          "in": "path"
          "schema":
            "enum":
              - "json"
              - "ttl"
              - "n-triples"
      "responses":
        "'200'":
          "content":
            "application/rdf+json":
              "schema":
                "type": "object"
                "properties":
                  "@context":
                    "type": "object"
                  "@graph":
                    "type": "array"
                    "items":
                      "type": "object"
                      "properties":
                        "@id":
                          "type": "string"
                        "@type":
                          "type": "string"
                          "example": "skos:Concept"
                        "openskos:uuid":
                          "type": "string"
                        "skos:notation":
                          "type": "string"
                        "openskos:status":
                          "type": "string"
                        "openskos:tenant":
                          "type": "string"
                        "dcterms:title":
                          "type": "string"
                        "skos:prefLabel":
                          "type": "string"
                        "skos:altLabel":
                          "type": "string"
                        "skos:hiddenLabel":
                          "type": "string"
                        "skosxl:prefLabel":
                          "type": "string"
                        "skosxl:altLabel":
                          "type": "string"
                        "skosxl:hiddenLabel":
                          "type": "string"
            "text/turtle":
              "schema":
                "type": "object"
                "properties":
                  "@context":
                    "type": "object"
                  "@graph":
                    "type": "array"
                    "items":
                      "type": "object"
                      "properties":
                        "@id":
                          "type": "string"
                        "@type":
                          "type": "string"
                          "example": "skos:Concept"
                        "openskos:uuid":
                          "type": "string"
                        "skos:notation":
                          "type": "string"
                        "openskos:status":
                          "type": "string"
                        "openskos:tenant":
                          "type": "string"
                        "dcterms:title":
                          "type": "string"
                        "skos:prefLabel":
                          "type": "string"
                        "skos:altLabel":
                          "type": "string"
                        "skos:hiddenLabel":
                          "type": "string"
                        "skosxl:prefLabel":
                          "type": "string"
                        "skosxl:altLabel":
                          "type": "string"
                        "skosxl:hiddenLabel":
                          "type": "string"
            "application/n-triples":
              "schema":
                "type": "object"
                "properties":
                  "@context":
                    "type": "object"
                  "@graph":
                    "type": "array"
                    "items":
                      "type": "object"
                      "properties":
                        "@id":
                          "type": "string"
                        "@type":
                          "type": "string"
                          "example": "skos:Concept"
                        "openskos:uuid":
                          "type": "string"
                        "skos:notation":
                          "type": "string"
                        "openskos:status":
                          "type": "string"
                        "openskos:tenant":
                          "type": "string"
                        "dcterms:title":
                          "type": "string"
                        "skos:prefLabel":
                          "type": "string"
                        "skos:altLabel":
                          "type": "string"
                        "skos:hiddenLabel":
                          "type": "string"
                        "skosxl:prefLabel":
                          "type": "string"
                        "skosxl:altLabel":
                          "type": "string"
                        "skosxl:hiddenLabel":
                          "type": "string"
    post:
      "summary": "Create one or more new concepts"
      "parameters":
        - "type": "string"
          "name": "format"
          "example": "json"
          "in": "path"
          "schema":
            "enum":
              - "json"
              - "ttl"
              - "n-triples"
        - "type": "object"
          "name": "@context"
          "in": "body"
        - "type": "array"
          "items":
            "type": "object"
            "properties":
              "@id":
                "type": "string"
              "@type":
                "type": "string"
                "example": "skos:Concept"
              "openskos:uuid":
                "type": "string"
              "skos:notation":
                "type": "string"
              "openskos:status":
                "type": "string"
              "openskos:tenant":
                "type": "string"
              "dcterms:title":
                "type": "string"
              "skos:prefLabel":
                "type": "string"
              "skos:altLabel":
                "type": "string"
              "skos:hiddenLabel":
                "type": "string"
              "skosxl:prefLabel":
                "type": "string"
              "skosxl:altLabel":
                "type": "string"
              "skosxl:hiddenLabel":
                "type": "string"
          "name": "@graph"
          "in": "body"
      "responses":
        "'200'":
          "content":
            "application/rdf+json":
              "schema":
                "type": "object"
                "properties":
                  "@context":
                    "type": "object"
                  "@graph":
                    "type": "array"
                    "items":
                      "type": "object"
                      "properties":
                        "@id":
                          "type": "string"
                        "@type":
                          "type": "string"
                          "example": "skos:Concept"
                        "openskos:uuid":
                          "type": "string"
                        "skos:notation":
                          "type": "string"
                        "openskos:status":
                          "type": "string"
                        "openskos:tenant":
                          "type": "string"
                        "dcterms:title":
                          "type": "string"
                        "skos:prefLabel":
                          "type": "string"
                        "skos:altLabel":
                          "type": "string"
                        "skos:hiddenLabel":
                          "type": "string"
                        "skosxl:prefLabel":
                          "type": "string"
                        "skosxl:altLabel":
                          "type": "string"
                        "skosxl:hiddenLabel":
                          "type": "string"
    put:
      "summary": ""
  /autocomplete.{format}:
    get:
      "summary": ""
  /labels.{format}:
    get:
      "summary": ""
  /label/{id}.{format}:
    get:
      "summary": ""
  /label.{format}:
    get:
      "summary": ""
  /users.{format}:
    get:
      "summary": ""
  /user/{id}.{format}:
    get:
      "summary": ""
  /statuses.{format}:
    get:
      "summary": ""
  /institutions.{format}:
    get:
      "summary": ""
    post:
      "summary": ""
    put:
      "summary": ""
  /institution/{id}.{format}:
    get:
      "summary": ""
    delete:
      "summary": ""
  /prefixes.{format}:
    get:
      "summary": ""
  /sets.{format}:
    get:
      "summary": ""
    post:
      "summary": ""
    put:
      "summary": ""
  /set/{id}.{format}:
    get:
      "summary": ""
    delete:
      "summary": ""
  /relations.{format}:
    get:
      "summary": ""
    post:
      "summary": "Create one or more semantic relations"
      "parameters":
        - "type": "string"
          "name": "format"
          "example": "json"
          "in": "path"
          "schema":
            "enum":
              - "json"
              - "ttl"
              - "n-triples"
        - "type": "object"
          "name": "@context"
          "in": "body"
        - "type": "array"
          "name": "@graph"
          "in": "body"
      "responses":
        "'200'":
          "content":
            "application/rdf+json":
              "schema":
                "type": "object"
                "properties":
                  "@context":
                    "type": "object"
                  "@graph":
                    "type": "array"
                    "items":
                      "type": "object"
                      "properties":
                        "@id":
                          "type": "string"
                        "@type":
                          "type": "string"
                          "example": "skos:Concept"
                        "openskos:uuid":
                          "type": "string"
                        "skos:notation":
                          "type": "string"
                        "openskos:status":
                          "type": "string"
                        "openskos:tenant":
                          "type": "string"
                        "dcterms:title":
                          "type": "string"
                        "skos:prefLabel":
                          "type": "string"
                        "skos:altLabel":
                          "type": "string"
                        "skos:hiddenLabel":
                          "type": "string"
                        "skosxl:prefLabel":
                          "type": "string"
                        "skosxl:altLabel":
                          "type": "string"
                        "skosxl:hiddenLabel":
                          "type": "string"
    put:
      "summary": "Update an existing relation"
    delete:
      "summary": "Delete one or more relations"
      "parameters":
        - "type": "string"
          "name": "format"
          "example": "json"
          "in": "path"
          "schema":
            "enum":
              - "json"
              - "ttl"
              - "n-triples"
        - "type": "string"
          "name": "object"
          "in": "query"
        - "type": "string"
          "name": "predicate"
          "in": "query"
        - "type": "string"
          "name": "subject"
          "in": "query"
      "responses":
        "'200'":
          "content":
            "application/rdf+json":
              "schema":
                "type": "object"
                "properties":
                  "@context":
                    "type": "object"
                  "@graph":
                    "type": "array"
                    "items":
                      "type": "object"
                      "properties":
                        "@id":
                          "type": "string"
                        "@type":
                          "type": "string"
                          "example": "skos:Concept"
                        "openskos:uuid":
                          "type": "string"
                        "skos:notation":
                          "type": "string"
                        "openskos:status":
                          "type": "string"
                        "openskos:tenant":
                          "type": "string"
                        "dcterms:title":
                          "type": "string"
                        "skos:prefLabel":
                          "type": "string"
                        "skos:altLabel":
                          "type": "string"
                        "skos:hiddenLabel":
                          "type": "string"
                        "skosxl:prefLabel":
                          "type": "string"
                        "skosxl:altLabel":
                          "type": "string"
                        "skosxl:hiddenLabel":
                          "type": "string"
  /conceptschemes.{format}:
    get:
      "summary": ""
    post:
      "summary": ""
    put:
      "summary": ""
  /conceptscheme/{id}.{format}:
    get:
      "summary": ""
    delete:
      "summary": ""
  /ping:
    get:
      "summary": "Healthcheck end basic information"
      "responses":
        "'200'":
          "content":
            "application/json":
              "schema":
                "type": "object"
                "properties":
                  "name":
                    "type": "string"
                    "example": "openskos-api"
                    "description": "Name of the whole api being called"
                  "status":
                    "type": "string"
                    "example": "ok"
                    "description": "Status of the api"
                  "version":
                    "type": "string"
                    "example": "2.3"
                    "description": "Version of the api"
                  "license":
                    "type": "string"
                    "example": "MIT"
                    "description": "License the api operates under"
                  "copyright":
                    "type": "object"
                    "properties":
                      "holder":
                        "type": "string"
                        "example": "Picturae"
                        "description": "Holder of the copyright"
                      "published":
                        "type": "integer"
                        "format": "int64"
                        "description": "The year the copyright was published"
                      "revised":
                        "type": "integer"
                        "format": "int64"
                        "description": "The year the copyright was revised"
                    "description": "Copyright information"
