parameters:
  ontology.dc:
    name: Dc
    prefix: dc
    namespace: 'http://purl.org/dc/elements/1.1/'
    properties:
      creator:
        datatype: resource
        resourcetype: "foaf:Person"
      contributor:
        datatype: resource
        resourcetype: "foaf:Person"
      title:
        datatype: literal
        literaltype: 'xsd:string'
