parameters:
  ontology.foaf:
    name: Foaf
    prefix: foaf
    namespace: 'http://xmlns.com/foaf/0.1/'
    properties:
      Person:
        datatype: class
        dataclass: App\OpenSkos\User\User
      name:
        datatype: literal
        literaltype: 'xsd:string'
      mbox:
        datatype: literal
        literaltype: 'xsd:string'
        regex: '^/[A-Z0-9._%+-]++@[A-Z0-9.-]++\.[A-Z]{2,}+$/i'
