parameters:
  ontology.openskos:
    name: OpenSkos
    prefix: openskos
    namespace: 'http://openskos.org/xmlns#'
    hasVocabulary: true
    properties:
      dataType:
        datatype: literal
        literaltype: "xsd:string"
        "dcterms:description": "The type of data that's supposed to go in the described field"
      literalType:
        datatype: literal
        literaltype: "xsd:string"
        "dcterms:description": "What kind of literal the described field is supposed to be"
      resourceType:
        datatype: literal
        literaltype: "xsd:string"
        "dcterms:description": "What kind of resource the described field is supposed to be"
      tenant:
        datatype: literal
        literaltype: "xsd:string"
        regex: /[a-z]{1,4}/
        "dcterms:description": "A reference to an org:FormalOrganization by it's openskos:code field"
      status:
        datatype: literal
        literaltype: 'xsd:string'
        enum: '!status'
      toBeChecked:
        datatype: literal
      dateDeleted:
        datatype: literal
        literaltype: "xsd:dateTime"
      deletedBy:
        datatype: resource
        resourcetype: "foaf:Person"
      acceptedBy:
        datatype: resource
        resourcetype: "foaf:Person"
      modifiedBy:
        datatype: resource
        resourcetype: "foaf:Person"
      uuid:
        datatype: literal
        literaltype: "xsd:string"
        regex: /[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{12}/i
      set:
        datatype: resource
        dataclass: App\OpenSkos\Set\Set
        "rdf:type": "rdfs:Class"
      role:
        datatype: literal
      inSkosCollection:
        datatype: literal
      code:
        datatype: literal
        "dcterms:description": "Short unique identifier for an org:FormalOrganization"
      name:
        datatype: literal
        literaltype: "xsd:string"
      disableSearchInOtherTenants:
        datatype: literal
        literaltype: "xsd:boolean"
      enableStatussesSystem:
        datatype: literal
        literaltype: "xsd:boolean"
      allow_oai:
        datatype: literal
        literaltype: "xsd:boolean"
      oai_baseURL:
        datatype: literal
        literaltype: "xsd:string"
      conceptBaseUri:
        datatype: literal
        literaltype: "xsd:string"
      licenceURL:
        datatype: literal
        literaltype: "xsd:string"
      webpage:
        datatype: literal
        literaltype: "xsd:string"
      enableskosxl:
        datatype: literal
        literaltype: "xsd:boolean"
      notationuniquepertenant:
        datatype: literal
      notationautogenerated:
        datatype: literal
      usertype:
        datatype: literal
        literaltype: 'xsd:string'
        enum: '!usertypes'
      apikey:
        datatype: literal
        literaltype: "xsd:string"


      isReplacedBy:
        datatype: resource
      replaces:
        datatype: resource
      inCollection:
        datatype: resource
      inSet:
        datatype: resource

      errorCode:
        datatype: literal
        literaltype: "xsd:string"
      error:
        datatype: class
        "rdf:Property":
          - "dcterms:description"
          - "http:sc"
          - "openskos:errorCode"
          - "rdf:Property"

    const:
      statuses: '!status'

    status:
      - candidate
      - approved
      - redirected
      - not_compliant
      - rejected
      - obsolete
      - deleted

    usertypes:
      - api
      - editor
      - both
