parameters:
  ontology.openskos:
    name: OpenSkos
    prefix: openskos
    namespace: 'http://openskos.org/xmlns#'
    hasVocabulary: true
    properties:
      datatype:
        datatype: literal
        "dcterms:description": "The type of data that's supposed to go in the described field"
      tenant:
        datatype: literal
        literaltype: "xsd:string"
        "dcterms:description": "A reference to an org:FormalOrganization by it's openskos:code field"
      status:
        datatype: literal
      toBeChecked:
        datatype: literal
      dateDeleted:
        datatype: literal
      deletedBy:
        datatype: resource
      acceptedBy:
        datatype: resource
      modifiedBy:
        datatype: resource
      uuid:
        datatype: literal
        literaltype: "xsd:string"
        regex: /[0-9a-f]{8}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{4}\-[0-9a-f]{12}/i
      set:
        datatype: resource
        dataclass: App\OpenSkos\Set\Set
        "rdf:type": "rdfs:Class"
      role:
        datatype: literal
      inSkosCollection:
        datatype: literal
      code:
        datatype: literal
        "dcterms:description": "Short unique identifier for an org:FormalOrganization"
      name:
        datatype: literal
      disableSearchInOtherTenants:
        datatype: literal
        literaltype: "xsd:boolean"
      enableStatussesSystem:
        datatype: literal
      allow_oai:
        datatype: literal
      oai_baseURL:
        datatype: literal
      conceptBaseUri:
        datatype: literal
      licenceURL:
        datatype: literal
      webpage:
        datatype: literal
      enableskosxl:
        datatype: literal
      notationuniquepertenant:
        datatype: literal
      notationautogenerated:
        datatype: literal
      usertype:
        datatype: literal
      apikey:
        datatype: literal


      isReplacedBy:
        datatype: resource
      replaces:
        datatype: resource
      inCollection:
        datatype: resource
      inSet:
        datatype: resource

      errorCode:
        datatype: literal
      error:
        datatype: class
        "rdf:Property":
          - "dcterms:description"
          - "http:sc"
          - "openskos:errorCode"
          - "rdf:Property"

    const:
      statuses:
        type: list
        source: status

    status:
      - candidate
      - approved
      - redirected
      - not_compliant
      - rejected
      - obsolete
      - deleted
