parameters:
  ontology.openskos:
    name: OpenSkos
    prefix: openskos
    namespace: 'http://openskos.org/xmlns#'
    hasVocabulary: true
    properties:
      dataType:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
        "rdfs:comment": "The type of data that's supposed to go in the described field"
      tenant:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
        "rdfs:comment": "A reference to an org:FormalOrganization by it's openskos:code field"
      status:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      toBeChecked:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      dateDeleted:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      deletedBy:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      acceptedBy:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      modifiedBy:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      uuid:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      set:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      role:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      inSkosCollection:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      code:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
        "rdfs:comment": "Short unique identifier for an org:FormalOrganization"
      name:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      disableSearchInOtherTenants:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      enableStatussesSystem:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      allow_oai:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      oai_baseURL:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      conceptBaseUri:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      licenceURL:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      webpage:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      enableskosxl:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      notationuniquepertenant:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      notationautogenerated:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      usertype:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"
      apikey:
        dataType: literal
        "rdf:type": "owl:ObjectProperty"


      isReplacedBy:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      replaces:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      inCollection:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"
      inSet:
        dataType: resource
        "rdf:type": "owl:ObjectProperty"

    const:
      statuses:
        type: list
        source: status

    status:
      - candidate
      - approved
      - redirected
      - not_compliant
      - rejected
      - obsolete
      - deleted
