parameters:
  ontology.org:
    name: Org
    prefix: org
    namespace: 'http://www.w3.org/ns/org#'
    properties:
      FormalOrganization:
        datatype: class
        dataclass: App\OpenSkos\Institution\Institution
