parameters:
  ontology.owl:
    name: Owl
    prefix: owl
    namespace: 'http://www.w3.org/2002/07/owl#'
    properties:
      ObjectProperty:
        datatype: resource
      Ontology:
        datatype: class
      SymmetricProperty:
        datatype: class
      TransitiveProperty:
        datatype: class
