parameters:
  ontology.skosxl:
    name: SkosXl
    prefix: skosxl
    namespace: 'http://www.w3.org/2008/05/skos-xl#'
    properties:
      Label:
        datatype: class
        dataclass: App\OpenSkos\Label\Label
      altLabel:
        datatype: literal
        literaltype: "xsd:string"
        "rdfs:range": "skosxl:Label"
      hiddenLabel:
        datatype: literal
        literaltype: "xsd:string"
        "rdfs:range": "skosxl:Label"
      labelRelation:
        datatype: resource
        "rdfs:range": "skosxl:Label"
        "rdfs:domain": "skosxl:Label"
      literalForm:
        datatype: literal
        "rdfs:domain": "skosxl:Label"
      prefLabel:
        datatype: literal
        literaltype: "xsd:string"
        "rdfs:range": "skosxl:Label"
