parameters:
  ontology.vcard:
    name: VCard
    prefix: vcard
    namespace: 'http://www.w3.org/2006/vcard/ns#'
    properties:
      ORG:
        datatype: literal
      orgname:
        datatype: literal
      orgunit:
        datatype: literal
      URL:
        datatype: literal
      EMAIL:
        datatype: literal
      ADR:
        datatype: literal
      Street:
        datatype: literal
      Locality:
        datatype: literal
      Pcode:
        datatype: literal
      Country:
        datatype: literal
