parameters:
  ontology.xsd:
    name: Xsd
    prefix: xsd
    namespace: 'http://www.w3.org/2001/XMLSchema#'
    properties:
      nonNegativeInteger:
        datatype: class
      boolean:
        datatype: class
      string:
        datatype: class
      dateTime:
        datatype: class
      integer:
        datatype: class
      decimal:
        datatype: class
